### ISSUE TITLE
This is not safe!

### ISSUE THREAD

**Issue by ironfroggy** [eligrey/jsandbox#10]
Web Workers are not sandboxed! They run with the same origin as the host page and, as such, have access to all the same cookies, IndexedDB (still not implemented in all browsers, but being added), and the ability to make trusted AJAX requests to the origin domain including POSTs.

Please consider rebranding the purpose of this project because it can *not* be used to run untrusted code safely and anyone using ti as such is putting their site and their users in danger!

**Comment by eligrey** [comment]
Um, the whole point of this repo is to block access to the unsafe things. It's an abandoned project at the moment, but you should know that it is definitely possible to dereference the methods necessary to access IndexedDB. Also, XHR is already disabled in jsandbox, did you not read the source code?

**Comment by eligrey** [comment]
I'll keep the issue open simply because this project is unmaintained (so jsandbox is not safe), but your premise that it is impossible to secure a worker is incorrect.

**Comment by ironfroggy** [comment]
Great, as long as there is a warning. The dereferencing is not effective. It can be trivially worked around.

`(function(){return this;})().__proto__.fetch(...)`

And, more annoying, even if you dereference on the prototype you can still just walk another step up

`(function(){return this;})().__proto__.__proto__.fetch(...)`

In any case, new functionality is always added so a blacklist implementation can never really remain safe. Thanks for leaving the issue open to make that clear to anyone.

**Comment by fabiocbinbutter** [comment]
@ironfroggy I'm trying to do something similar. The blacklist can be converted to a whilelist by iterating and dereferencing everything that you don't explicitly allow. The proto properties could also be dereferenced, such as `this.__proto__.fetch=undefined;` . At this point, would there be any further workarounds?

**Comment by josephg** [comment]
It might be worth adding a warning in the readme that the project isn't safe. Not everyone will check the issues.

**Comment by Rob-pw** [comment]
Might this be mitigated by recursive traversal and removal of all properties, such as `__proto__` all the way up the tree? As described in: https://www.softfluent.com/blog/dev/Executing-untrusted-JavaScript-code-in-a-browser
